In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sms
import os
import inspect
import string

In [2]:
substances = pd.read_csv('C:/Users/tup54227/Downloads/audit_dudit.csv', header = 0)
substances.loc[(substances['RealID']==1244)]

,RealID,audit_1,audit_2,audit_3,audit_4,audit_5,audit_6,audit_7,audit_8,audit_9,...,dudit_4,dudit_5,dudit_6,dudit_7,dudit_8,dudit_9,dudit_10,dudit_11,Notes,dudit_drugtype
19,1244,5.0,1.0,5.0,1.0,1.0,1.0,1.0,3.0,1.0,...,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...",1

In [3]:
#function to input column name from Excel and output column number
def col2num(col):
    num = 0
    for c in col:
        if c in string.ascii_letters:
            num = num * 26 + (ord(c.upper()) - ord('A')) + 1
    return num - 1

#function to replace mis-coded AUDIT/DUDIT data with the correct integer values
def replace_num(foo):
    try:
        foo = int(foo)
        vals = {1:0, 3:1, 4:2, 5:3, 6:4}
        return vals[foo]
    except: return foo
    
#function to replace AUDIT_2 specifically
def replace_2(foo):
    try:
        foo = int(foo)
        vals = {1:0, 2:1, 3:2, 4:3, 5:4}
        return vals[foo]
    except: return foo
    
#function to replace slightly differently scored mis-coded data from AUDIT/DUDIT last two columns
def replace_extra(foo):
    try:
        foo = int(foo)
        vals = {1:0, 3:2, 4:4}
        return vals[foo]
    except: return foo
    
#The below script defines the column ranges from Excel for each section of the AUDIT and DUDIT, and prints them for later use 
audit = (col2num('D'),col2num('J'))
dudit = (col2num('V'),col2num('AD'))
audit_end = (col2num('J'),col2num('L'))
dudit_end = (col2num('AD'),col2num('AF'))

print(audit,'\n',dudit,'\n',audit_end,'\n',dudit_end)

(3, 9)
 (21, 29)
 (9, 11)
 (29, 31)

In [8]:
#In a copy of the substances dataframe, the values are rescored correctly using the previous functions

sub_copy = substances.copy()
    
#audit q3-q8
for n in range(3,9):
    col = sub_copy.iloc[:,n]
    new_col = list(map(replace_num, col))
    sub_copy.iloc[:,n] = new_col

#audit q1
single_col = sub_copy['audit_1']
new_single_col = list(map(replace_num, single_col))
sub_copy['audit_1'] = new_single_col
    
#audit q2
single_col = sub_copy['audit_2']
new_single_col = list(map(replace_2, single_col))
sub_copy['audit_2'] = new_single_col
    
#dudit q2-q9
for n in range(21,29):
    col = sub_copy.iloc[:,n]
    new_col = list(map(replace_num, col))
    sub_copy.iloc[:,n] = new_col

#dudit q1
single_col = sub_copy['dudit_1']
new_single_col = list(map(replace_num, single_col))
sub_copy['dudit_1'] = new_single_col

#audit q9-q10
for n in range(9,11):
    col = sub_copy.iloc[:,n]
    new_col = list(map(replace_extra, col))
    sub_copy.iloc[:,n] = new_col

#dudit q10-q11
for n in range(29,31):
    col = sub_copy.iloc[:,n]
    new_col = list(map(replace_extra, col))
    sub_copy.iloc[:,n] = new_col

#the dataframe is then cut to only include the relevant columns, and the ID column is changed to a name that matches other dataframes, on which it's merged
# sub_copy.drop(sub_copy.columns[col2num('B'):col2num('BX')], axis=1, inplace = True)
# sub_copy = sub_copy.rename(columns = {'RealID':'sub'})
# sub_copy.drop(sub_copy.columns[1], axis=1, inplace = True)
sub_copy

,RealID,audit_1,audit_2,audit_3,audit_4,audit_5,audit_6,audit_7,audit_8,audit_9,...,dudit_4,dudit_5,dudit_6,dudit_7,dudit_8,dudit_9,dudit_10,dudit_11,Notes,dudit_drugtype
0,1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,audit/duditaskedinREDCap,NaN
1,1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,audit/duditaskedinREDCap,NaN
2,1003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,audit/duditaskedinREDCap,NaN
3,1004,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,1006,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,3210,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...",0
58,3212,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...",0
59,3218,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,...,4.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...","1,2"
60,3220,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...",0
61,3223,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"audit(questionsQ145-Q154)Dudit(questionsQ157,1...",0

In [9]:
#Here the AUDIT, DUDIT, AADIS, and 7U7D data are merged into one dataframe, and output to a .csv file

# SUSD = pd.read_csv('./7U7D.csv').rename(columns = {'participant_id':'sub'})
# AADIS = pd.read_csv('./AADIS.csv').rename(columns = {'participant_id':'sub'})

# SubnMood = SUSD.merge(sub_copy, on = 'sub', how = 'right').sort_values('sub', ascending = True, ignore_index = True)
# SubnMood = SubnMood.merge(AADIS, on = 'sub', how = 'left').sort_values('sub', ascending = True, ignore_index = True)
# SubnMood.to_csv('Substance_and_Mood_data.csv', index = False)
# pd.read_csv('./Substance_and_Mood_data.csv')
# SubnMood.loc[(SubnMood['sub']==1244) & SubnMood['audit_1']]

sub_copy.to_csv('AUDIT_DUDIT_rescored.csv', index = False)